In [1]:
%matplotlib inline
%load_ext fireducks.pandas
import pandas as pd

In [3]:
df = pd.read_excel("./datasets/complete-2020.xlsx",index_col=0)

No todos los set de datos incluyen la primera columna como un indice, por lo que si no lo tiene se puede omitir la primera linea de lectura de datos.

In [4]:
df.head()

,day,views,redViews,comments,likes,dislikes,videosAddedToPlaylists,videosRemovedFromPlaylists,shares,estimatedMinutesWatched,...,subscribersGained,subscribersLost,estimatedRevenue,estimatedAdRevenue,grossRevenue,estimatedRedPartnerRevenue,monetizedPlaybacks,playbackBasedCpm,adImpressions,cpm
0,2020-01-01,38,0,1,1,0,0,0,0,202,...,0,0,0.0,0.0,0.0,0.0,0,0.0,0,0.0
1,2020-01-02,28,1,0,1,0,1,0,13,81,...,1,0,0.0,0.0,0.0,0.0,0,0.0,0,0.0
2,2020-01-03,16,1,1,0,0,0,0,0,41,...,0,0,0.0,0.0,0.0,0.0,0,0.0,0,0.0
3,2020-01-04,8,0,0,0,0,0,0,0,12,...,1,0,0.0,0.0,0.0,0.0,0,0.0,0,0.0
4,2020-01-05,18,0,0,0,0,0,0,0,19,...,0,0,0.0,0.0,0.0,0.0,0,0.0,0,0.0

In [5]:
df.tail()

,day,views,redViews,comments,likes,dislikes,videosAddedToPlaylists,videosRemovedFromPlaylists,shares,estimatedMinutesWatched,...,subscribersGained,subscribersLost,estimatedRevenue,estimatedAdRevenue,grossRevenue,estimatedRedPartnerRevenue,monetizedPlaybacks,playbackBasedCpm,adImpressions,cpm
361,2020-12-27,1338,86,1,24,1,13,5,1,2953,...,18,1,1.899,1.796,3.266,0.103,323,10.111,352,9.278
362,2020-12-28,1389,116,4,41,0,6,2,5,4231,...,7,2,2.163,1.973,3.587,0.190,348,10.307,377,9.515
363,2020-12-29,1292,92,7,33,6,9,4,1,2855,...,8,4,2.361,2.228,4.051,0.133,388,10.441,415,9.761
364,2020-12-30,1245,78,6,21,2,12,6,10,2315,...,9,2,2.449,2.380,4.328,0.069,334,12.958,375,11.541
365,2020-12-31,1125,78,3,8,1,15,7,3,2834,...,8,2,1.580,1.518,2.760,0.062,328,8.415,343,8.047

In [6]:
df

,day,views,redViews,comments,likes,dislikes,videosAddedToPlaylists,videosRemovedFromPlaylists,shares,estimatedMinutesWatched,...,subscribersGained,subscribersLost,estimatedRevenue,estimatedAdRevenue,grossRevenue,estimatedRedPartnerRevenue,monetizedPlaybacks,playbackBasedCpm,adImpressions,cpm
0,2020-01-01,38,0,1,1,0,0,0,0,202,...,0,0,0.000,0.000,0.000,0.000,0,0.000,0,0.000
1,2020-01-02,28,1,0,1,0,1,0,13,81,...,1,0,0.000,0.000,0.000,0.000,0,0.000,0,0.000
2,2020-01-03,16,1,1,0,0,0,0,0,41,...,0,0,0.000,0.000,0.000,0.000,0,0.000,0,0.000
3,2020-01-04,8,0,0,0,0,0,0,0,12,...,1,0,0.000,0.000,0.000,0.000,0,0.000,0,0.000
4,2020-01-05,18,0,0,0,0,0,0,0,19,...,0,0,0.000,0.000,0.000,0.000,0,0.000,0,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,2020-12-27,1338,86,1,24,1,13,5,1,2953,...,18,1,1.899,1.796,3.266,0.103,323,10.111,352,9.278
362,2020-12-28,1389,116,4,41,0,6,2,5,4231,...,7,2,2.163,1.973,3.587,0.190,348,10.307,377,9.515
363,2020-12-29,1292,92,7,33,6,9,4,1,2855,...,8,4,2.361,2.228,4.051,0.133,388,10.441,415,9.761
364,2020-12-30,1245,78,6,21,2,12,6,10,2315,...,9,2,2.449,2.380,4.328,0.069,334,12.958,375,11.541
365,2020-12-31,1125,78,3,8,1,15,7,3,2834,...,8,2,1.580,1.518,2.760,0.062,328,8.415,343,8.047

en la columna date el valor es un string, pero esta en formato de fecha, por lo que se puede convertir a un formato de fecha con la funcion pd.to_datetime

In [7]:
df["day"]
# para acceder a una columna, esto se hace de forma muy similar a un diccionario, y se puede acceder a una columna por su nombre. retorna toda la columna

0      2020-01-01
1      2020-01-02
2      2020-01-03
3      2020-01-04
4      2020-01-05
          ...
361    2020-12-27
362    2020-12-28
363    2020-12-29
364    2020-12-30
365    2020-12-31
Name: day, Length: 366, dtype: object

In [8]:
df["day"]=pd.to_datetime(df["day"],format="%Y-%m-%d")

In [10]:
df.dtypes # los objetos normalmente son strings

day                               datetime64[ns]
views                                      int64
redViews                                   int64
comments                                   int64
likes                                      int64
dislikes                                   int64
videosAddedToPlaylists                     int64
videosRemovedFromPlaylists                 int64
shares                                     int64
estimatedMinutesWatched                    int64
estimatedRedMinutesWatched                 int64
averageViewDuration                        int64
averageViewPercentage                    float64
annotationClickThroughRate                 int64
annotationCloseRate                        int64
annotationImpressions                      int64
annotationClickableImpressions             int64
annotationClosableImpressions              int64
annotationClicks                           int64
annotationCloses                           int64
cardClickRate                            float64
cardTeaserClickRate                      float64
cardImpressions                            int64
cardTeaserImpressions                      int64
cardClicks                                 int64
cardTeaserClicks                           int64
subscribersGained                          int64
subscribersLost                            int64
estimatedRevenue                         float64
estimatedAdRevenue                       float64
grossRevenue                             float64
estimatedRedPartnerRevenue               float64
monetizedPlaybacks                         int64
playbackBasedCpm                         float64
adImpressions                              int64
cpm                                      float64
dtype: object

In [11]:
df.shape # retorna la cantidad de filas y columnas, y no incluye la columna de indices

(366, 36)

In [12]:
df.to_csv("./complete-2020.csv")