In [1]:
%matplotlib inline
%load_ext fireducks.pandas
import pandas as pd

In [2]:
df = pd.read_excel("./datasets/complete-2020.xlsx",index_col=0)
df["day"]=pd.to_datetime(df["day"],format="%Y-%m-%d")
df.head()

,day,views,redViews,comments,likes,dislikes,videosAddedToPlaylists,videosRemovedFromPlaylists,shares,estimatedMinutesWatched,...,subscribersGained,subscribersLost,estimatedRevenue,estimatedAdRevenue,grossRevenue,estimatedRedPartnerRevenue,monetizedPlaybacks,playbackBasedCpm,adImpressions,cpm
0,2020-01-01,38,0,1,1,0,0,0,0,202,...,0,0,0.0,0.0,0.0,0.0,0,0.0,0,0.0
1,2020-01-02,28,1,0,1,0,1,0,13,81,...,1,0,0.0,0.0,0.0,0.0,0,0.0,0,0.0
2,2020-01-03,16,1,1,0,0,0,0,0,41,...,0,0,0.0,0.0,0.0,0.0,0,0.0,0,0.0
3,2020-01-04,8,0,0,0,0,0,0,0,12,...,1,0,0.0,0.0,0.0,0.0,0,0.0,0,0.0
4,2020-01-05,18,0,0,0,0,0,0,0,19,...,0,0,0.0,0.0,0.0,0.0,0,0.0,0,0.0

In [3]:
df.describe()

,views,redViews,comments,likes,dislikes,videosAddedToPlaylists,videosRemovedFromPlaylists,shares,estimatedMinutesWatched,estimatedRedMinutesWatched,...,subscribersGained,subscribersLost,estimatedRevenue,estimatedAdRevenue,grossRevenue,estimatedRedPartnerRevenue,monetizedPlaybacks,playbackBasedCpm,adImpressions,cpm
count,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,...,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000
mean,605.800546,30.674863,7.661202,13.609290,0.461749,7.464481,2.109290,1.412568,1356.442623,81.590164,...,4.770492,0.587432,0.461694,0.412527,0.750008,0.013541,90.762295,1.863776,98.598361,1.713049
std,505.269754,30.116045,35.134263,12.933246,0.845560,8.205083,3.003937,2.308236,1133.044656,97.071115,...,4.098353,1.005059,0.995606,0.793608,1.442852,0.034010,174.137328,3.592728,189.077834,3.297243
min,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,96.000000,4.000000,0.000000,2.000000,0.000000,1.000000,0.000000,0.000000,234.000000,6.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,506.000000,23.000000,2.000000,11.500000,0.000000,6.000000,1.000000,1.000000,1233.500000,47.000000,...,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1126.750000,52.000000,5.000000,21.000000,1.000000,12.000000,3.000000,2.000000,2346.250000,118.500000,...,8.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1572.000000,156.000000,453.000000,74.000000,6.000000,74.000000,33.000000,21.000000,4231.000000,489.000000,...,18.000000,6.000000,9.811000,2.766000,5.028000,0.219000,613.000000,12.958000,667.000000,11.541000

In [4]:
df["views"].describe()

count     366.000000
mean      605.800546
std       505.269754
min         7.000000
25%        96.000000
50%       506.000000
75%      1126.750000
max      1572.000000
Name: views, dtype: float64

In [5]:
df.sort_values("views",ascending=False).head()

,day,views,redViews,comments,likes,dislikes,videosAddedToPlaylists,videosRemovedFromPlaylists,shares,estimatedMinutesWatched,...,subscribersGained,subscribersLost,estimatedRevenue,estimatedAdRevenue,grossRevenue,estimatedRedPartnerRevenue,monetizedPlaybacks,playbackBasedCpm,adImpressions,cpm
305,2020-11-01,1572,111,5,23,1,27,4,2,3812,...,15,1,1.931,1.780,3.236,0.151,520,6.223,559,5.789
302,2020-10-29,1552,91,16,32,1,18,8,2,3229,...,16,5,2.339,2.275,4.137,0.063,613,6.749,667,6.202
315,2020-11-11,1546,64,230,49,2,26,13,0,4097,...,18,5,1.540,1.511,2.748,0.029,392,7.010,420,6.543
323,2020-11-19,1517,83,139,55,0,29,11,2,3589,...,12,2,3.584,2.152,3.913,0.072,528,7.411,564,6.938
284,2020-10-11,1516,76,32,74,0,13,10,3,3451,...,15,1,0.000,0.000,0.000,0.000,0,0.000,0,0.000

para ordenar los datos a traves de multiples columnas, se puede usar la funcion sort_values() de pandas. 
```python
df.sort_values(by=['col1', 'col2'], ascending=[True, False])
```

In [7]:
df.sort_values(["views","estimatedMinutesWatched"],ascending=[False,False]).head()

,day,views,redViews,comments,likes,dislikes,videosAddedToPlaylists,videosRemovedFromPlaylists,shares,estimatedMinutesWatched,...,subscribersGained,subscribersLost,estimatedRevenue,estimatedAdRevenue,grossRevenue,estimatedRedPartnerRevenue,monetizedPlaybacks,playbackBasedCpm,adImpressions,cpm
305,2020-11-01,1572,111,5,23,1,27,4,2,3812,...,15,1,1.931,1.780,3.236,0.151,520,6.223,559,5.789
302,2020-10-29,1552,91,16,32,1,18,8,2,3229,...,16,5,2.339,2.275,4.137,0.063,613,6.749,667,6.202
315,2020-11-11,1546,64,230,49,2,26,13,0,4097,...,18,5,1.540,1.511,2.748,0.029,392,7.010,420,6.543
323,2020-11-19,1517,83,139,55,0,29,11,2,3589,...,12,2,3.584,2.152,3.913,0.072,528,7.411,564,6.938
284,2020-10-11,1516,76,32,74,0,13,10,3,3451,...,15,1,0.000,0.000,0.000,0.000,0,0.000,0,0.000